// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwqxiqgwmmznolhwycwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53cXhpcWd3bW16bm9saHd5Y3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDMwNDgsImV4cCI6MjA2MDExOTA0OH0.oc3-b5vaKAc3lQfQFybZOAXm4wD2dUIl6L81kbRaMmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);